(function adminV32(){
"use strict";
const db=window.clubSupabase,$=id=>document.getElementById(id);
const state={user:null,admin:null,stats:{},clients:[],rules:[],claims:[],selectedId:null,toastTimer:null,searchTimer:null};
const labels={vapers:"Club Vapers",jerseys:"Club Jerseys",perfumes:"Club Perfumes",importb2b:"Club IMPORTB2B"};
const rulesText={vapers:"Compra + historia verificada = +1 punto. Metas: 3, 6 y 9.",jerseys:"Compra + historia verificada = +1 punto. Metas: 4 y 8.",perfumes:"Compra + historia verificada = +1 punto. Metas: 3, 6 y 10.",importb2b:"Compra de $30.000 o más + historia verificada = +1 punto."};
const viewTitles={dashboard:"Resumen general",clients:"Gestión de clientes",rewards:"Reglas y premios",claims:"Premios desbloqueados"};
const statDefs=[["clients_total","Clientes totales","Personas únicas"],["clients_active","Clientes activos","Miembros habilitados"],["valid_actions_total","Puntos registrados","Suma de todos los clubes"],["rewards_pending","Premios pendientes","Pendientes de entrega"],["club_vapers","Club Vapers","Membresías activas"],["club_jerseys","Club Jerseys","Membresías activas"],["club_perfumes","Club Perfumes","Membresías activas"],["club_importb2b","Club IMPORTB2B","Membresías activas"]];
const eventLabels={client_created:"Ingreso al club",client_updated:"Actualización",verified_purchase_story:"Compra + historia verificada",reward_unlocked:"Premio desbloqueado",reward_delivered:"Premio entregado",status_change:"Cambio de estado",other:"Movimiento"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmtN=v=>new Intl.NumberFormat("es-AR").format(Number(v||0));
const fmtD=(v,time=false)=>{if(!v)return"—";const d=new Date(String(v).length===10?v+"T12:00:00":v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",...(time?{timeStyle:"short"}:{})}).format(d)};
const fmtM=v=>v==null||v===""?"—":new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(v));
const localDate=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const totalPoints=c=>(c.clubs||[]).reduce((s,x)=>s+Number(x.points||0),0);
const activeClubs=c=>(c.clubs||[]).filter(x=>x.is_active);
function toast(m,type){const t=$("toast");if(!t){alert(m);return}t.textContent=m;t.className=`toast is-visible${type==="error"?" is-error":""}`;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.className="toast",3800)}
function loading(btn,on,text){if(!btn)return;if(on){btn.dataset.old=btn.textContent;btn.disabled=true;btn.textContent=text||"Procesando..."}else{btn.disabled=false;btn.textContent=btn.dataset.old||btn.textContent}}
function showView(v){document.querySelectorAll(".admin-view").forEach(x=>x.classList.remove("is-active"));document.querySelectorAll(".nav-button").forEach(x=>x.classList.remove("is-active"));$(`view-${v}`)?.classList.add("is-active");document.querySelector(`.nav-button[data-view="${v}"]`)?.classList.add("is-active");$("viewTitle").textContent=viewTitles[v]||"Panel";document.querySelector(".admin-sidebar")?.classList.remove("is-open");$("menuButton")?.setAttribute("aria-expanded","false")}
async function ensureAdmin(){if(!window.CLUB_CONFIG_READY||!db){$("adminLoading").innerHTML='<strong>Falta configurar Supabase</strong>';return false}const u=await db.auth.getUser();if(u.error||!u.data.user){location.replace("/admin/login");return false}const a=await db.from("admins").select("id,full_name,is_active").eq("id",u.data.user.id).maybeSingle();if(a.error||!a.data?.is_active){await db.auth.signOut();location.replace("/admin/login");return false}state.user=u.data.user;state.admin=a.data;return true}
async function loadStats(){const {data,error}=await db.rpc("admin_get_stats_v3");if(error)throw error;state.stats=data||{};$("statsGrid").innerHTML=statDefs.map(([k,l,n])=>`<article class="stat-card"><small>${esc(l)}</small><strong>${fmtN(state.stats[k])}</strong><span>${esc(n)}</span></article>`).join("")}
async function loadClients(q=""){const {data,error}=await db.rpc("admin_search_clients_v3",{p_query:q});if(error)throw error;state.clients=Array.isArray(data)?data:[];renderClients();renderRecent()}
function clubChips(c){const a=c.clubs||[];return a.length?a.map(x=>`<span class="club-pill club-pill--small">${esc(labels[x.club_type]||x.club_type)}</span>`).join(" "):"<small>Sin club</small>"}
function clubProgress(c){const a=c.clubs||[];return a.length?a.map(x=>`<div class="mc-admin-progress"><span>${esc(labels[x.club_type]||x.club_type)}</span><strong>${fmtN(x.points)}</strong></div>`).join(""):"—"}
function renderClients(){const b=$("clientsTableBody");$("clientsEmpty").hidden=state.clients.length>0;b.innerHTML=state.clients.map(c=>`<tr><td><div class="table-client"><strong>${esc(c.full_name)}</strong><small>${esc(c.instagram_username?"@"+c.instagram_username:c.phone||"Sin contacto")}</small></div></td><td><div class="mc-chip-wrap">${clubChips(c)}</div></td><td><strong>${esc(c.client_code)}</strong></td><td>${clubProgress(c)}</td><td><span class="status-badge ${c.is_active?"is-active":"is-inactive"}">${c.is_active?"Activo":"Inactivo"}</span></td><td><div class="table-actions"><button class="table-button" data-client-action="open" data-client-id="${c.id}">Abrir</button><button class="table-button" data-client-action="copy" data-client-id="${c.id}">Copiar link</button></div></td></tr>`).join("")}
function renderRecent(){const a=state.clients.slice(0,6);$("recentClients").innerHTML=a.length?a.map(c=>`<button class="compact-item text-button" type="button" data-open-client="${c.id}"><span class="compact-item__main"><strong>${esc(c.full_name)}</strong><small>${activeClubs(c).length} club${activeClubs(c).length===1?"":"es"} · ${fmtN(totalPoints(c))} puntos</small></span><span class="status-badge ${c.is_active?"is-active":"is-inactive"}">${c.is_active?"Activo":"Inactivo"}</span></button>`).join(""):'<div class="empty-state">Todavía no hay clientes.</div>'}
async function loadRules(){const {data,error}=await db.rpc("admin_get_reward_rules");if(error)throw error;state.rules=Array.isArray(data)?data:[];const order=["vapers","jerseys","perfumes","importb2b"];$("rulesGrid").innerHTML=order.map(t=>`<article class="panel rule-card"><div class="rule-card__header"><div><span class="eyebrow">${esc(labels[t])}</span><h2>${esc(labels[t])}</h2></div><span class="club-pill">+1 por validación</span></div><p>${esc(rulesText[t])}</p><div class="rule-milestones">${state.rules.filter(r=>r.club_type===t).map(r=>`<div class="rule-milestone"><span>${r.milestone} pts</span><div><strong>${esc(r.reward_name)}</strong><small>${esc(r.reward_description)}</small></div></div>`).join("")}</div></article>`).join("")}
async function loadClaims(){const {data,error}=await db.rpc("admin_get_reward_claims",{p_status:null});if(error)throw error;state.claims=Array.isArray(data)?data:[];renderClaims();renderPending()}
function renderClaims(){const b=$("claimsTableBody");$("claimsEmpty").hidden=state.claims.length>0;b.innerHTML=state.claims.map(c=>`<tr><td><strong>${esc(c.client_name)}</strong><br><small>${esc(c.client_code)}</small></td><td><span class="club-pill club-pill--small">${esc(labels[c.club_type]||c.club_type)}</span></td><td><strong>${esc(c.reward_name)}</strong></td><td>${fmtN(c.milestone)} puntos</td><td><span class="status-badge ${c.status==="delivered"?"is-active":"is-pending"}">${c.status==="delivered"?"Entregado":"Pendiente"}</span></td><td>${esc(fmtD(c.unlocked_at))}</td><td><button class="table-button" data-claim-action="toggle" data-claim-id="${c.id}">${c.status==="delivered"?"Marcar pendiente":"Marcar entregado"}</button></td></tr>`).join("")}
function renderPending(){const a=state.claims.filter(x=>x.status==="pending").slice(0,6);$("pendingClaims").innerHTML=a.length?a.map(c=>`<button class="compact-item text-button" data-go-view="claims"><span class="compact-item__main"><strong>${esc(c.client_name)}</strong><small>${esc(c.reward_name)} · ${fmtN(c.milestone)} puntos</small></span><span class="status-badge is-pending">Pendiente</span></button>`).join(""):'<div class="empty-state">No hay premios pendientes.</div>'}
function resetForm(){$("clientForm").reset();$("clientId").value="";$("clientJoinedAt").value=localDate();$("clientClub").value="vapers";$("clientClub").disabled=false;$("clientFormTitle").textContent="Crear cliente";$("clientFormMessage").textContent="";const small=$("clientClub")?.parentElement?.querySelector("small");if(small)small.textContent="Este será el primer club. Después podés agregar otros desde la ficha."}
function openCreate(){resetForm();$("clientDialog").showModal()}
function openEdit(c){$("clientId").value=c.id;$("clientFullName").value=c.full_name||"";$("clientPhone").value=c.phone||"";$("clientInstagram").value=c.instagram_username?"@"+c.instagram_username:"";$("clientJoinedAt").value=c.joined_at||localDate();$("clientNotes").value=c.internal_notes||"";$("clientClub").value=(c.clubs?.[0]?.club_type)||"vapers";$("clientClub").disabled=true;$("clientFormTitle").textContent="Editar cliente";$("clientFormMessage").textContent="Los clubes se administran desde la ficha del cliente.";$("clientDialog").showModal()}
async function saveClient(e){e.preventDefault();const btn=$("saveClientButton"),id=$("clientId").value,name=$("clientFullName").value.trim(),phone=$("clientPhone").value.trim(),ig=$("clientInstagram").value.trim(),joined=$("clientJoinedAt").value,notes=$("clientNotes").value.trim(),club=$("clientClub").value;if(name.length<2||!joined){$("clientFormMessage").textContent="Completa nombre y fecha.";return}try{loading(btn,true,"Guardando...");let res;if(id){res=await db.rpc("admin_update_client_v3",{p_client_id:id,p_full_name:name,p_phone:phone||null,p_instagram_username:ig||null,p_joined_at:joined,p_internal_notes:notes||null})}else{const found=await db.rpc("admin_find_existing_client",{p_instagram:ig||null,p_phone:phone||null});if(found.error)throw found.error;if(found.data?.length){const ex=found.data[0],clubs=await db.rpc("admin_get_client_clubs",{p_client_id:ex.id});if(clubs.error)throw clubs.error;if((clubs.data||[]).some(x=>x.club_type===club))throw new Error(`${ex.full_name} ya existe y ya pertenece a ${labels[club]}.`);if(confirm(`${ex.full_name} ya existe con código ${ex.client_code}.\n\n¿Agregarlo a ${labels[club]} sin crear otro cliente?`)){res=await db.rpc("admin_add_client_to_club",{p_client_id:ex.id,p_club_type:club});if(res.error)throw res.error;$("clientDialog").close();await refreshAll();toast("Cliente existente agregado al nuevo club.");return}else{return}}res=await db.rpc("admin_create_client_v3",{p_full_name:name,p_phone:phone||null,p_instagram_username:ig||null,p_joined_at:joined,p_internal_notes:notes||null,p_club_type:club})}if(res.error)throw res.error;$("clientDialog").close();await refreshAll();toast(id?"Cliente actualizado.":"Cliente creado con 0 puntos.")}catch(err){console.error(err);$("clientFormMessage").textContent=err.message||"No se pudo guardar."}finally{loading(btn,false)}}
function selected(){return state.clients.find(c=>c.id===state.selectedId)||null}
function ensureDetailExtras(){let box=$("detailClubMemberships");if(!box){box=document.createElement("div");box.id="detailClubMemberships";box.className="club-memberships";document.querySelector(".client-detail-header")?.after(box)}let add=$("addClubButton");if(!add){add=document.createElement("button");add.id="addClubButton";add.type="button";add.className="button button--primary";add.textContent="+ Agregar a otro club";document.querySelector(".client-detail-actions")?.prepend(add)}let sel=$("actionClub");if(!sel){const lab=document.createElement("label");lab.className="form-field";lab.innerHTML='<span>Club de esta compra</span><select id="actionClub" required></select>';$("actionForm")?.querySelector(".panel-heading")?.after(lab);sel=$("actionClub")}return {box,add,sel}}
function renderDetail(c){const {box,sel}=ensureDetailExtras();$("detailClientName").textContent=c.full_name;$("detailClientCode").textContent=c.client_code;$("detailClientStatus").textContent=c.is_active?"Activo":"Inactivo";$("detailClientStatus").className=`status-badge ${c.is_active?"is-active":"is-inactive"}`;$("detailClientClub").textContent=`${(c.clubs||[]).length} club${(c.clubs||[]).length===1?"":"es"}`;$("detailClientContact").textContent=[c.phone,c.instagram_username?"@"+c.instagram_username:""].filter(Boolean).join(" · ")||"Sin contacto";$("detailPoints").textContent=fmtN(totalPoints(c));$("detailValidActions").textContent=fmtN(totalPoints(c));$("detailPendingRewards").textContent=fmtN(state.claims.filter(x=>x.client_id===c.id&&x.status==="pending").length);$("toggleSelectedClient").textContent=c.is_active?"Desactivar":"Reactivar";box.innerHTML=(c.clubs||[]).map(x=>`<article class="club-membership"><small>${esc(labels[x.club_type]||x.club_type)}</small><strong>${fmtN(x.points)} puntos</strong><span>${x.is_active?"Membresía activa":"Membresía inactiva"}</span></article>`).join("");sel.innerHTML=activeClubs(c).map(x=>`<option value="${x.club_type}">${esc(labels[x.club_type])} · ${fmtN(x.points)} puntos</option>`).join("");updatePurchaseClub();$("actionObservation").value="";$("actionPurchaseAmount").value=""}
async function openClient(id){const c=state.clients.find(x=>x.id===id);if(!c)return;state.selectedId=id;renderDetail(c);$("clientDetailDialog").showModal();await loadHistory(id)}
async function loadHistory(id){$("adminClientHistory").innerHTML='<div class="empty-state">Cargando historial...</div>';const {data,error}=await db.rpc("admin_get_client_history",{p_client_id:id});if(error){$("adminClientHistory").innerHTML='<div class="empty-state">No se pudo cargar el historial.</div>';return}const a=Array.isArray(data)?data:[];$("adminClientHistory").innerHTML=a.length?a.map(h=>{const club=h.metadata?.club_type;return `<article class="history-item"><div class="history-dot"></div><div class="history-item__content"><div class="history-item__header"><strong>${esc(eventLabels[h.event_type]||"Movimiento")}</strong>${club?`<span class="club-pill club-pill--small">${esc(labels[club]||club)}</span>`:""}</div><p>${esc(h.description)}</p>${h.metadata?.purchase_amount?`<small class="history-extra">Monto: ${esc(fmtM(h.metadata.purchase_amount))}</small>`:""}${h.metadata?.observation?`<small class="history-extra">${esc(h.metadata.observation)}</small>`:""}<div class="history-item__meta"><time>${esc(fmtD(h.created_at,true))}</time><span>${esc(h.admin_name||"Administrador")}</span></div></div></article>`}).join(""):'<div class="empty-state">Todavía no hay movimientos.</div>'}
function updatePurchaseClub(){const t=$("actionClub")?.value||"";$("actionClubRule").textContent=rulesText[t]||"";$("purchaseAmountField").hidden=t!=="importb2b";$("actionPurchaseAmount").required=t==="importb2b"}
async function registerPurchase(e){e.preventDefault();const c=selected(),t=$("actionClub")?.value;if(!c||!t)return;const btn=$("saveActionButton"),raw=$("actionPurchaseAmount").value.trim(),amount=raw?Number(raw):null,obs=$("actionObservation").value.trim();if(t==="importb2b"&&(!Number.isFinite(amount)||amount<30000)){toast("Club IMPORTB2B requiere una compra mínima de $30.000.","error");return}try{loading(btn,true,"Registrando...");const {data,error}=await db.rpc("admin_register_verified_purchase_v3",{p_client_id:c.id,p_club_type:t,p_purchase_amount:amount,p_observation:obs||null});if(error)throw error;await refreshAll();const r=selected();if(r)renderDetail(r);await loadHistory(c.id);toast(data?.reward_unlocked?`+1 punto en ${labels[t]}. Premio: ${data.reward_unlocked}`:`+1 punto registrado en ${labels[t]}.`)}catch(err){console.error(err);toast(err.message||"No se pudo registrar.","error")}finally{loading(btn,false)}}
async function addClub(){const c=selected();if(!c)return;const owned=new Set((c.clubs||[]).map(x=>x.club_type)),available=Object.keys(labels).filter(t=>!owned.has(t));if(!available.length){toast("Este cliente ya pertenece a todos los clubes.");return}let d=$("addClubDialogV32");if(!d){d=document.createElement("dialog");d.id="addClubDialogV32";d.className="modal";d.innerHTML='<form id="addClubFormV32" class="modal-card"><div class="modal-heading"><div><span class="eyebrow">MULTI-CLUB</span><h2>Agregar a otro club</h2></div><button class="icon-button" type="button" id="closeAddClubV32">×</button></div><label class="form-field"><span>Nuevo club</span><select id="newClubV32"></select></label><div class="form-actions"><button class="button button--primary" type="submit">Agregar club</button></div></form>';document.body.appendChild(d);$("closeAddClubV32").onclick=()=>d.close();$("addClubFormV32").onsubmit=async e=>{e.preventDefault();try{const {error}=await db.rpc("admin_add_client_to_club",{p_client_id:state.selectedId,p_club_type:$("newClubV32").value});if(error)throw error;d.close();await refreshAll();const x=selected();if(x)renderDetail(x);toast("Club agregado correctamente.")}catch(err){toast(err.message||"No se pudo agregar.","error")}}}$("newClubV32").innerHTML=available.map(t=>`<option value="${t}">${esc(labels[t])}</option>`).join("");d.showModal()}
async function toggleStatus(){const c=selected();if(!c)return;if(!confirm(`${c.is_active?"Desactivar":"Reactivar"} a ${c.full_name}?`))return;const {error}=await db.rpc("admin_set_client_status_v3",{p_client_id:c.id,p_is_active:!c.is_active});if(error){toast(error.message,"error");return}await refreshAll();const x=selected();if(x)renderDetail(x);toast("Estado actualizado.")}
async function deleteClient(){const c=selected();if(!c)return;if(!confirm(`Eliminar definitivamente a ${c.full_name}?\n\nEsto también elimina su historial y membresías.`))return;const {error}=await db.rpc("admin_delete_client",{p_client_id:c.id});if(error){toast(error.message,"error");return}$("clientDetailDialog").close();state.selectedId=null;await refreshAll();toast("Cliente eliminado.")}
async function copyLink(c){const url=`${location.origin}/c/${encodeURIComponent(c.access_token)}`;try{await navigator.clipboard.writeText(url);toast("Enlace copiado.")}catch{prompt("Copiá este enlace:",url)}}
async function toggleClaim(id){const c=state.claims.find(x=>x.id===id);if(!c)return;const status=c.status==="delivered"?"pending":"delivered";const {error}=await db.rpc("admin_update_reward_claim_status",{p_claim_id:id,p_status:status,p_notes:c.notes||null});if(error){toast(error.message,"error");return}await Promise.all([loadClaims(),loadStats()]);toast(status==="delivered"?"Premio marcado como entregado.":"Premio vuelto a pendiente.")}
async function refreshAll(){await Promise.all([loadClients($("clientSearch")?.value||""),loadStats(),loadClaims()])}
function bind(){document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));document.addEventListener("click",e=>{const gv=e.target.closest("[data-go-view]");if(gv)showView(gv.dataset.goView);const oc=e.target.closest("[data-open-client]");if(oc)openClient(oc.dataset.openClient);const ca=e.target.closest("[data-client-action]");if(ca){const c=state.clients.find(x=>x.id===ca.dataset.clientId);if(!c)return;if(ca.dataset.clientAction==="open")openClient(c.id);else copyLink(c)}const cl=e.target.closest("[data-claim-action]");if(cl)toggleClaim(cl.dataset.claimId)});document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.closeDialog)?.close()));$("createClientButton")?.addEventListener("click",openCreate);$("quickCreateButton")?.addEventListener("click",openCreate);$("clientForm")?.addEventListener("submit",saveClient);$("actionForm")?.addEventListener("submit",registerPurchase);$("editSelectedClient")?.addEventListener("click",()=>{const c=selected();if(c)openEdit(c)});$("toggleSelectedClient")?.addEventListener("click",toggleStatus);$("deleteSelectedClient")?.addEventListener("click",deleteClient);$("copyClientLink")?.addEventListener("click",()=>{const c=selected();if(c)copyLink(c)});$("logoutButton")?.addEventListener("click",async()=>{await db.auth.signOut();location.replace("/admin/login")});$("menuButton")?.addEventListener("click",()=>{const s=document.querySelector(".admin-sidebar"),open=s?.classList.toggle("is-open");$("menuButton").setAttribute("aria-expanded",String(!!open))});$("clientSearch")?.addEventListener("input",e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>loadClients(e.target.value),250)});document.addEventListener("change",e=>{if(e.target.id==="actionClub")updatePurchaseClub()});document.addEventListener("click",e=>{if(e.target.id==="addClubButton")addClub()})}
async function init(){try{if(!await ensureAdmin())return;$("adminName").textContent=state.admin.full_name;$("adminEmail").textContent=state.user.email||"—";$("adminInitials").textContent=(state.admin.full_name||"AD").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();bind();await Promise.all([loadStats(),loadClients(""),loadRules(),loadClaims()]);$("adminLoading").hidden=true;$("adminApp").hidden=false}catch(err){console.error(err);$("adminLoading").innerHTML=`<strong>No se pudo cargar el panel</strong><span>${esc(err.message||"Error inesperado")}</span>`}}
init();
})();
